import java.util.Scanner;

public class randomnumber {
	
	public static void main(String[] args) {
		
		Scanner sc = new Scanner(System.in);
		while (true ) {
			
			
			System.out.print("\n\nTry to guess a number 1 to 20 generated by the computer.\n\nNumber: ");
	
			int num1user = sc.nextInt();
			
			if (0 <= num1user && num1user <= 20) {
			
				System.out.print("Number generated by the computer: ");
				int num2comp = 0 + (int)(Math.random() * ((20 - 0) + 1));
		
				System.out.print(num2comp + "\nDifference between the number u chose and the number generated: " + (num2comp - num1user) );
			} else {
				System.out.println("\nError! The number u wrote is not between 0 and 20. Try different ones.");
			}
		}
	}
}
